/**
 * seed-alerts.js  (v2)
 * Generates realistic synthetic high-risk ActivityLog records.
 *
 * Improvements over v1:
 *  - Timestamps use proper business-hours distribution (most activity 9am-6pm)
 *    with realistic off-hours spikes for truly suspicious events.
 *  - Risk scores are role-aware: admins flag lower (70-82) since they SHOULD
 *    touch sensitive resources, interns/staff flag higher (72-98).
 *  - Score distribution is weighted (most logs 70-84, fewer critical).
 *  - Cleans up previously seeded records before inserting fresh ones.
 *
 * Run: node backend/scripts/seed-alerts.js
 */

require("dotenv").config({ path: require("path").join(__dirname, "../.env") });

const { sequelize } = require("../config/database");
const ActivityLog   = require("../models/ActivityLog");
const User          = require("../models/User");
const { Op }        = require("sequelize");

// ── Pools ─────────────────────────────────────────────────────────────────────

// Actions that are ONLY generated by this script — used to identify & clean old seeds
const SYNTHETIC_ACTIONS = [
  "UNAUTHORIZED_ACCESS",
  "DATA_EXFILTRATION_ATTEMPT",
  "BRUTE_FORCE_DETECTED",
  "PRIVILEGE_ESCALATION",
  "SUSPICIOUS_LOGIN",
  "MASS_DOWNLOAD",
  "API_ABUSE",
  "OFF_HOURS_ACCESS",
  "SENSITIVE_FILE_ACCESS",
  "CONFIG_TAMPERING",
  "CREDENTIAL_STUFFING",
  "ANOMALOUS_BEHAVIOR",
];

// Subset that implies off-hours activity (will get late-night timestamps)
const OFF_HOURS_ACTIONS = new Set([
  "DATA_EXFILTRATION_ATTEMPT",
  "CREDENTIAL_STUFFING",
  "BRUTE_FORCE_DETECTED",
  "OFF_HOURS_ACCESS",
  "ANOMALOUS_BEHAVIOR",
]);

// Actions also created by real business logic — keep these in the pool but don't clean them up
const BUSINESS_ACTIONS = [
  "ACCOUNT_LOCKOUT",    // real events too
  "ACCOUNT_UNBLOCK",    // real events too
  "DELETE_USER",        // real events too
  "ADMIN_OPERATION",
];

const ALL_ACTIONS = [...SYNTHETIC_ACTIONS, ...BUSINESS_ACTIONS];

const RESOURCES = [
  "Employee Records DB",
  "Payroll System",
  "HR Confidential Docs",
  "Source Code Repository",
  "Customer PII Export",
  "Financial Reports Q4",
  "Admin Panel /root",
  "Cloud Storage Bucket",
  "Auth Service Config",
  "API Key Vault",
  "Network Logs Archive",
  "Sensitive Data Pipeline",
  "Board Meeting Minutes",
  "Audit Trail Export",
  "Production Database",
];

const IP_POOL = [
  "192.168.1.44",
  "10.0.0.215",
  "172.16.5.88",
  "203.88.12.7",
  "45.33.200.11",
  "91.134.56.23",
  "185.220.101.42",    // known Tor exit node
  "105.234.67.90",
  "193.32.161.5",
  "23.105.178.246",
  "77.88.55.66",
  "31.13.160.1",
];

const USER_AGENTS = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120",
  "curl/7.88.1",
  "python-requests/2.31.0",
  "Postman/10.18.0",
  "Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.36",
  "Scrapy/2.11.0",
  "Go-http-client/1.1",
  "python-httpx/0.27",
];

const DECISIONS_WEIGHTED = [
  "BLOCK", "BLOCK", "BLOCK",
  "REVIEW", "REVIEW",
];

const STATUS_MAP = {
  BLOCK:  ["FAILED", "FAILED", "FAILED"],
  REVIEW: ["FAILED", "SUCCESS"],
  ALLOW:  ["SUCCESS"],
};

const DEPARTMENTS = ["IT", "HR", "ACCOUNTS", "MARKETING"];

// ── Helpers ──────────────────────────────────────────────────────────────────

const pick    = (arr) => arr[Math.floor(Math.random() * arr.length)];
const randInt = (lo, hi) => Math.floor(Math.random() * (hi - lo + 1)) + lo;

/**
 * Weighted risk score by role.
 * Admins/seniors doing suspicious things get 70-82 (they legitimately touch
 * sensitive resources, so risk engine rates them lower).
 * Staff 72-90, Interns 75-98 (no business need for sensitive access).
 */
function riskByRole(role) {
  switch (role) {
    case "admin":
    case "super_admin": return randInt(70, 82);
    case "senior":      return randInt(70, 87);
    case "staff":       return randInt(72, 92);
    case "intern":
    default:            return randInt(75, 99);
  }
}

/**
 * Generate a realistic timestamp:
 *  - 65% of records during business hours (Mon-Fri 09:00-18:30 IST)
 *  - 20% during evening fringe (18:30-22:00)
 *  - 15% during late night / weekend (truly suspicious)
 * Spread across last 35 days.
 */
function realisticDate(action, daysBack = 35) {
  // Pick a base day
  const dayOffset = randInt(0, daysBack);
  const base = new Date();
  base.setDate(base.getDate() - dayOffset);
  base.setSeconds(randInt(0, 59));
  base.setMilliseconds(0);

  const dow = base.getDay(); // 0=Sun, 6=Sat
  const isWeekend = dow === 0 || dow === 6;

  // Off-hours actions always get suspicious times
  if (OFF_HOURS_ACTIONS.has(action)) {
    if (isWeekend) {
      // Weekend + off-hours = middle of the night
      base.setHours(randInt(1, 4));
      base.setMinutes(randInt(0, 59));
    } else {
      // Weekday late night
      const h = Math.random() < 0.6 ? randInt(22, 23) : randInt(1, 5);
      base.setHours(h);
      base.setMinutes(randInt(0, 59));
    }
    return base;
  }

  if (isWeekend) {
    // Non-off-hours on weekend = someone working late/weekend (evening)
    base.setHours(randInt(10, 21));
    base.setMinutes(randInt(0, 59));
    return base;
  }

  // Weekday — weighted distribution
  const bucket = Math.random();
  if (bucket < 0.65) {
    // Business hours 09:00 - 18:29
    base.setHours(randInt(9, 17));
    base.setMinutes(randInt(0, 59));
  } else if (bucket < 0.85) {
    // Evening fringe 18:30 - 21:59
    base.setHours(18);
    base.setMinutes(randInt(30, 59));
    if (Math.random() > 0.5) base.setHours(randInt(19, 21));
  } else {
    // Suspicious: late night or very early morning
    const h = Math.random() < 0.5 ? randInt(22, 23) : randInt(0, 6);
    base.setHours(h);
    base.setMinutes(randInt(0, 59));
  }

  return base;
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  await sequelize.authenticate();
  console.log("✅  Connected to PostgreSQL\n");

  // 1. Clean up previously seeded synthetic records
  const deleted = await ActivityLog.destroy({
    where: { action: { [Op.in]: SYNTHETIC_ACTIONS } }
  });
  console.log(`🗑️   Removed ${deleted} old synthetic records`);

  // 2. Fetch real users
  const users = await User.findAll({
    attributes: ["id", "email", "department", "role"],
    order: [["id", "ASC"]],
  });

  if (users.length === 0) {
    console.error("❌  No users found. Create users first.");
    process.exit(1);
  }

  console.log(`👤  Found ${users.length} users\n`);

  // 3. Build records
  const TOTAL   = 70;
  const records = [];
  const stats   = { byDecision: {}, byRole: {}, byHour: {} };

  for (let i = 0; i < TOTAL; i++) {
    const user       = pick(users);
    const action     = pick(ALL_ACTIONS);
    const decision   = pick(DECISIONS_WEIGHTED);
    const status     = pick(STATUS_MAP[decision] || ["FAILED"]);
    const riskScore  = riskByRole(user.role);
    const resource   = pick(RESOURCES);
    const ip         = pick(IP_POOL);
    const userAgent  = pick(USER_AGENTS);
    const department = user.department || pick(DEPARTMENTS);
    const createdAt  = realisticDate(action);

    records.push({
      userId:    user.id,
      action,
      resource,
      ipAddress: ip,
      userAgent,
      riskScore,
      department,
      decision,
      status,
      resolved:  false,
      createdAt,
      updatedAt: createdAt,
    });

    // Stats
    stats.byDecision[decision] = (stats.byDecision[decision] || 0) + 1;
    stats.byRole[user.role]    = (stats.byRole[user.role]    || 0) + 1;
    const h = createdAt.getHours();
    const bucket =
      h >= 9 && h < 18  ? "Business (09-18)" :
      h >= 18 && h < 22 ? "Evening  (18-22)" :
                           "Night    (22-09)";
    stats.byHour[bucket] = (stats.byHour[bucket] || 0) + 1;
  }

  // 4. Bulk-insert
  await ActivityLog.bulkCreate(records, { validate: true });

  // 5. Print summary
  const riskScores = records.map(r => r.riskScore);
  const avgRisk    = (riskScores.reduce((a, b) => a + b, 0) / riskScores.length).toFixed(1);
  const minRisk    = Math.min(...riskScores);
  const maxRisk    = Math.max(...riskScores);

  console.log(`✅  Seeded ${TOTAL} synthetic alerts\n`);
  console.log("── Risk Scores ─────────────────────────────");
  console.log(`   Avg: ${avgRisk}  Min: ${minRisk}  Max: ${maxRisk}`);
  console.log("   70-79:", riskScores.filter(r => r < 80).length, "records");
  console.log("   80-89:", riskScores.filter(r => r >= 80 && r < 90).length, "records");
  console.log("   90-99:", riskScores.filter(r => r >= 90).length, "records");
  console.log("\n── By Decision ─────────────────────────────");
  Object.entries(stats.byDecision).forEach(([k, v]) => console.log(`   ${k}: ${v}`));
  console.log("\n── By Role ─────────────────────────────────");
  Object.entries(stats.byRole).forEach(([k, v]) => console.log(`   ${k}: ${v}`));
  console.log("\n── By Time Bucket ──────────────────────────");
  Object.entries(stats.byHour).forEach(([k, v]) => console.log(`   ${k}: ${v}`));

  await sequelize.close();
}

main().catch(err => {
  console.error("❌  Seed failed:", err.message || err);
  process.exit(1);
});
